import assert from 'node:assert/strict';
import {expect} from 'playwright/test';
export default async function({page,browser,errors,base,restricted,out,transport}) {

const results=[],calls=[];
const fresh=async()=>{await page.goto(base+'/?test=1');await page.waitForFunction(()=>!!window.retailLab);};
const call=async(name,args={},p=page)=>{const out=await p.evaluate(async({name,args,transport})=>{const mc=document.modelContext,tools=await mc.getTools();const v=await mc.executeTool(tools.find(t=>t.name===name),(transport === 'chrome154-json' ? JSON.stringify(args) : args));return typeof v==='string'?JSON.parse(v):v;},{name,args,transport});calls.push({at:new Date().toISOString(),name,args,result:out,transport});return out;};
const test=async(name,fn)=>{try{await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:String(e)});}};
await fresh();
let c,r;
await test('native discovery exactly five tools',async()=>{const ts=await page.evaluate(async()=>(await document.modelContext.getTools()).map(t=>t.name));assert.deepEqual(ts,['compare_periods','create_report_draft','get_analysis_context','present_result','query_metrics']);});
await test('native compare and present golden totals',async()=>{c=await call('get_analysis_context');r=await call('compare_periods',{context_id:c.context_id});assert.equal(r.totals.base,100000000);assert.equal(r.totals.target,98000000);assert.equal(r.rows[0].id,'S03');assert.equal(await page.locator('#kpis').innerText(),'');const p=await call('present_result',{result_id:r.result_id,expected_view_version:c.view_version,view_type:'bar'});assert.equal(p.ok,true);await expect(page.locator('#kpis')).toContainText('98,000,000');await page.screenshot({path:`${out}/native-weekly.png`,fullPage:true});});
await test('native query metrics',async()=>{c=await call('get_analysis_context');const q=await call('query_metrics',{context_id:c.context_id,metric:'units',group_by:'category',filters:{store_ids:['S03'],category_ids:['C01']}});assert.equal(q.totals.value,8000);});
await test('native draft idempotency and prior UI edits preserved',async()=>{const a={result_ids:[r.result_id],title:'ネイティブ検証',notes:'原因は未確認。',idempotency_key:'mac-native-1'};let d=await call('create_report_draft',a);assert.equal(d.ok,true);await page.locator('.draft textarea').first().fill('人が編集した文章を保持');d=await call('create_report_draft',a);assert.equal(d.reused,true);assert.equal(await page.locator('.draft textarea').first().inputValue(),'人が編集した文章を保持');const bad=await call('create_report_draft',{...a,title:'different'});assert.equal(bad.error.code,'IDEMPOTENCY_CONFLICT');await call('create_report_draft',{...a,idempotency_key:'mac-native-2'});await expect(page.locator('.draft')).toHaveCount(2);assert.equal(await page.locator('.draft textarea').first().inputValue(),'人が編集した文章を保持');});
await test('native stale result refuses old AND substituted new version',async()=>{await fresh();c=await call('get_analysis_context');r=await call('compare_periods',{context_id:c.context_id});await page.selectOption('#metric','gross_profit');await page.selectOption('#stores',['S03']);const newer=await call('get_analysis_context');for(const v of [c.view_version,newer.view_version]){const p=await call('present_result',{result_id:r.result_id,expected_view_version:v,view_type:'bar'});assert.equal(p.error.code,'VIEW_CHANGED');}const freshResult=await call('compare_periods',{context_id:newer.context_id,group_by:'product'});assert.equal(freshResult.query.metric,'gross_profit');assert.deepEqual(freshResult.query.filters.store_ids,['S03']);const p=await call('present_result',{result_id:freshResult.result_id,expected_view_version:newer.view_version,view_type:'bar'});assert.equal(p.ok,true);await expect(page.locator('tbody tr')).toHaveCount(12);});
await test('native async reauthorization race refuses UI overwrite',async()=>{await fresh();c=await call('get_analysis_context');r=await call('compare_periods',{context_id:c.context_id});let release,entered;const blocked=new Promise(x=>entered=x);await page.route('**/api/result',async route=>{entered();await new Promise(x=>release=x);await route.continue();});const pending=call('present_result',{result_id:r.result_id,expected_view_version:c.view_version,view_type:'bar'});await blocked;await page.selectOption('#metric','gross_profit');release();const out=await pending;await page.unroute('**/api/result');assert.equal(out.error.code,'VIEW_CHANGED');assert.equal(await page.locator('#metric').inputValue(),'gross_profit');});
await test('native invalid arguments and missing period are rejected',async()=>{c=await call('get_analysis_context');const a=await call('compare_periods',{context_id:c.context_id,user_id:'admin'});assert.equal(a.error.code,'INVALID_ARGUMENT');const b=await call('compare_periods',{context_id:c.context_id,target_period:{start:'2026-09-14',end:'2026-09-18'}});assert.equal(b.error.code,'NO_DATA');});
await test('native restricted session denies S03 and other session result',async()=>{const ctx=await browser.newContext();const p=await ctx.newPage();try{await p.goto(restricted+'/?test=1');await p.waitForFunction(()=>!!window.retailLab);const rc=await call('get_analysis_context',{},p);assert.deepEqual(rc.allowed_store_ids,['S01']);const denied=await call('compare_periods',{context_id:rc.context_id,filters:{store_ids:['S03']}},p);assert.equal(denied.error.code,'FORBIDDEN');const draft=await call('create_report_draft',{result_ids:[r.result_id],title:'denied',notes:'',idempotency_key:'other-session'},p);assert.equal(draft.error.code,'RESULT_EXPIRED');assert.equal(await p.locator('.draft').count(),0);}finally{await ctx.close();}});
await test('native console explicitly selected transport tracks context and result',async()=>{await fresh();await page.locator('summary').first().click();await page.selectOption('#native-transport',transport);await page.locator('#native-run').click();await expect(page.locator('#tool-output')).toContainText('context_id');await page.selectOption('#tool-select','compare_periods');await page.locator('#sample-input').click();await page.locator('#native-run').click();await expect.poll(async()=>JSON.parse(await page.locator('#tool-output').innerText()).result_id).toMatch(/^r_/);await page.selectOption('#tool-select','present_result');await page.locator('#sample-input').click();const args=JSON.parse(await page.locator('#tool-input').inputValue());assert.ok(args.result_id.startsWith('r_'));await page.locator('#native-run').click();await expect(page.locator('#kpis')).toContainText('98,000,000');});
return results;
}
