import assert from 'node:assert/strict';
import {expect} from 'playwright/test';
export default async function({page,browser,errors,base,restricted,out,transport}) {
const results=[];
const test=async(name,fn)=>{try{await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:String(e)});}};
await page.goto(base+'/?test=1');await page.waitForFunction(()=>!!window.retailLab);
await test('S03 profit displays decrease and readable draft',async()=>{await page.selectOption('#stores',['S03']);await page.selectOption('#metric','gross_profit');await page.selectOption('#group','product');await page.locator('#compare').click();await expect(page.locator('#kpis')).toContainText('-624,000');await expect(page.locator('#kpis')).toContainText('減少 26.00%');await page.locator('#create-draft').click();await expect(page.locator('#draft-link')).toHaveText('未保存の下書き 1件');const text=await page.locator('.draft textarea').inputValue();assert.ok(text.includes('2,400,000円 → 1,776,000円'));assert.ok(!text.includes('context_id'));assert.ok(!text.includes('【'));});
await test('native conflict has actionable recovery; rereads actual conditions',async()=>{const stale=await page.evaluate(async(transport)=>{const mc=document.modelContext,t=await mc.getTools(),call=async(n,a)=>JSON.parse(await mc.executeTool(t.find(t=>t.name===n),(transport === 'chrome154-json' ? JSON.stringify(a) : a)));const c=await call('get_analysis_context',{});return {c,r:await call('compare_periods',{context_id:c.context_id})};},transport);await page.selectOption('#metric','net_sales');await page.evaluate(async({c,r,transport})=>{const mc=document.modelContext,t=await mc.getTools();await mc.executeTool(t.find(t=>t.name==='present_result'),transport === 'chrome154-json' ? JSON.stringify({result_id:r.result_id,expected_view_version:c.view_version,view_type:'bar'}) : {result_id:r.result_id,expected_view_version:c.view_version,view_type:'bar'});},{...stale,transport});await expect(page.locator('#retry')).toBeVisible();await page.locator('#retry').click();await expect(page.locator('#kpis')).toContainText('6,400,000');await expect(page.locator('#retry')).toBeHidden();assert.equal(await page.locator('#metric').inputValue(),'net_sales');const displayed=await page.evaluate(()=>window.retailLab.workspace.displayed);assert.notEqual(displayed.result_id,stale.r.result_id);});
await test('ratio difference is in percentage points',async()=>{await page.selectOption('#metric','gross_margin');await page.selectOption('#category','C01');await page.locator('#compare').click();await expect(page.locator('#kpis')).toContainText('30.00%');await expect(page.locator('#kpis')).toContainText('22.00%');await expect(page.locator('#kpis')).toContainText('増減（ポイント）');await expect(page.locator('#kpis')).toContainText('-8.00');await expect(page.locator('tbody')).toContainText('pt');});
await test('positive and zero differences are not labeled decreases',async()=>{await page.selectOption('#category','');await page.selectOption('#metric','net_sales');await page.locator('#monthly').click();await page.locator('#compare').click();await expect(page.locator('#kpis')).toContainText('+481,362');await expect(page.locator('#kpis')).toContainText('増加 2.26%');await page.locator('#weekly').click();await page.selectOption('#stores',['S04']);await page.locator('#compare').click();await expect(page.locator('#kpis')).toContainText('増減なし');});
await page.selectOption('#stores',['S03']);await page.selectOption('#metric','gross_profit');await page.locator('#compare').click();await expect(page.locator('#kpis')).toContainText('1,776,000');await page.screenshot({path:`${out}/final-desktop.png`,fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:`${out}/final-mobile.png`,fullPage:true});await page.setViewportSize({width:1440,height:1100});
return results;
}
