import assert from 'node:assert/strict';
import {expect} from 'playwright/test';
export default async function({page,browser,errors,base,restricted,out,transport}) {

const results=[];
const fresh=async()=>{await page.goto(base+'/?test=1&webmcp=off');await page.waitForFunction(()=>!!window.retailLab);};
const test=async(name,fn)=>{const start=Date.now();try{await fn();results.push({name,status:'PASS',ms:Date.now()-start});}catch(e){results.push({name,status:'FAIL',error:String(e)});}};
await test('real HTTP ordinary UI golden totals',async()=>{await fresh();await page.locator('#compare').click();await expect(page.locator('#kpis')).toContainText('98,000,000');await expect(page.locator('#kpis')).toContainText('100,000,000');await expect(page.locator('tbody tr')).toHaveCount(10);await expect(page.locator('tbody tr').first()).toContainText('S03');await page.screenshot({path:`${out}/ui-weekly.png`,fullPage:true});});
await test('UI and shared handler parity (not native)',async()=>{const v=await page.evaluate(async()=>{const {workspace:w,tools}=window.retailLab;const m=w.displayed,c=await tools[0].execute({}),q=await tools[1].execute({context_id:c.context_id});return {a:m.rows,b:q.rows,id:w.displayed.result_id,old:m.result_id};});assert.deepEqual(v.a,v.b);assert.equal(v.id,v.old);});
await test('UI change during pending presentation preserves gross profit',async()=>{await fresh();await page.locator('.diagnostics > summary').click();await page.locator('#race').click();await expect(page.locator('#notice')).toContainText('3秒保留中');await page.selectOption('#metric','gross_profit');await expect(page.locator('#notice')).toContainText('条件が変わったため',{timeout:7000});assert.equal(await page.locator('#metric').inputValue(),'gross_profit');assert.equal(await page.locator('#kpis').innerText(),'');await page.screenshot({path:`${out}/ui-conflict.png`,fullPage:true});});
await test('UI cancel prevents presentation',async()=>{await fresh();await page.locator('.diagnostics > summary').click();await page.locator('#race').click();await expect(page.locator('#notice')).toContainText('3秒保留中');await page.locator('#cancel').click();await expect(page.locator('#notice')).toContainText('集計を中止しました。');assert.equal(await page.locator('#kpis').innerText(),'');});
await test('undo increments version',async()=>{await fresh();await page.locator('#compare').click();await expect(page.locator('#view-version')).toHaveText('2');await page.locator('#undo').click();await expect(page.locator('#view-version')).toHaveText('3');assert.equal(await page.locator('#kpis').innerText(),'');});
await test('draft edit is preserved and treated as text',async()=>{await fresh();await page.locator('#compare').click();await expect(page.locator('#kpis')).toContainText('98,000,000');await page.locator('#create-draft').click();await expect(page.locator('.draft')).toHaveCount(1);await page.locator('.draft textarea').first().fill('編集保持 <img src=x onerror=alert(1)>');await page.locator('#create-draft').click();await expect(page.locator('.draft')).toHaveCount(2);assert.equal(await page.locator('.draft textarea').first().inputValue(),'編集保持 <img src=x onerror=alert(1)>');assert.equal(await page.locator('.draft img').count(),0);});
await test('monthly S03 product totals',async()=>{await fresh();await page.locator('#monthly').click();await page.selectOption('#stores',['S03']);await page.selectOption('#group','product');await page.locator('#compare').click();await expect(page.locator('tbody tr')).toHaveCount(12);await expect(page.locator('#result-provenance')).toContainText('2026-07-01');const r=await page.evaluate(()=>window.retailLab.workspace.displayed);assert.equal(r.rows.reduce((a,r)=>a+r.target,0),r.totals.target);});
await test('mobile width',async()=>{await page.setViewportSize({width:390,height:844});await fresh();await page.locator('#compare').click();await expect(page.locator('#kpis')).toContainText('98,000,000');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await page.screenshot({path:`${out}/ui-mobile.png`,fullPage:true});await page.setViewportSize({width:1440,height:1100});});
await test('no uncaught JS exceptions',async()=>assert.deepEqual(errors,[]));
return results;
}
