import test from 'node:test';
import assert from 'node:assert/strict';
import {Workspace} from '../static/dist/workspace.js';
import {definitions, validate, register} from '../static/dist/webmcp.js';
const session={csrf:'test',allowed_store_ids:['S01','S03'],dataset_snapshot_id:'fixture',data_through:'2026-09-13',business_as_of:'2026-09-18',base_period:{start:'2026-08-31',end:'2026-09-06'},target_period:{start:'2026-09-07',end:'2026-09-13'},categories:{C01:'飲料'},products:{'C01-P1':{category_id:'C01',name:'商品1'}},metrics:{net_sales:'円'}};
function fixture(){
 const cache=new Map();let i=0;
 const api=async(path,body)=>{
  if(path==='/api/result')return structuredClone(cache.get(body.result_id));
  const r={ok:true,result_id:'r'+ ++i,query_hash:'q'+i,query:{...structuredClone(body),kind:path==='/api/compare'?'compare':'query'},rows:[{id:'S03',label:'S03',base:8000000,target:6400000,delta:-1600000}],totals:{base:100000000,target:98000000,delta:-2000000},warnings:[],dataset_snapshot_id:'fixture',metric_definition_version:'v1',unit:'円',data_through:'2026-09-13',truncated:false};
  cache.set(r.result_id,r);return structuredClone(r);
 };
 return new Workspace(structuredClone(session),api);
}
const prepared=async w=>{const c=w.context();const r=await w.query({context_id:c.context_id},'compare');return {c,r};};
const presentation=(c,r)=>({result_id:r.result_id,expected_view_version:c.view_version,view_type:'bar'});
const draftArgs=r=>({result_ids:[r.result_id],title:'test',notes:'',idempotency_key:'same'});

test('context snapshots do not mutate workspace',()=>{const w=fixture(),c=w.context();c.filters.store_ids=[];assert.deepEqual(w.state.filters.store_ids,['S01','S03']);});
test('query does not change visible state',async()=>{const w=fixture(),s=structuredClone(w.state);await prepared(w);assert.deepEqual(w.state,s);assert.equal(w.version,1);assert.equal(w.displayed,null);});
test('present commits result and synchronously renders',async()=>{const w=fixture(),{c,r}=await prepared(w);let rendered=false;w.render=()=>{rendered=w.displayed?.result_id===r.result_id};await w.present(presentation(c,r));assert.equal(rendered,true);assert.equal(w.version,2);});
test('human change before query rejects old context',async()=>{const w=fixture(),c=w.context();w.humanChange({...w.state,metric:'gross_profit'});await assert.rejects(w.query({context_id:c.context_id},'compare'),{code:'STALE_CONTEXT'});});
test('human change between query and presentation is preserved',async()=>{const w=fixture(),{c,r}=await prepared(w);w.humanChange({...w.state,metric:'gross_profit'});await assert.rejects(w.present(presentation(c,r)),{code:'VIEW_CHANGED'});assert.equal(w.state.metric,'gross_profit');assert.equal(w.displayed,null);});
test('substituting new expected version cannot launder an old result',async()=>{const w=fixture(),{r}=await prepared(w);w.humanChange({...w.state,metric:'gross_profit'});await assert.rejects(w.present({result_id:r.result_id,expected_view_version:w.version,view_type:'bar'}),{code:'VIEW_CHANGED'});});
test('recheck after async result authorization closes commit race',async()=>{const w=fixture(),{c,r}=await prepared(w),api=w.api;let release;w.api=async(...args)=>{const out=await api(...args);await new Promise(r=>release=r);return out;};const pending=w.present(presentation(c,r));await new Promise(r=>setImmediate(r));w.humanChange({...w.state,metric:'gross_profit'});release();await assert.rejects(pending,{code:'VIEW_CHANGED'});});
test('query started before human change returns stale, unpresentable result',async()=>{const w=fixture(),c=w.context(),api=w.api;let release;w.api=async(...args)=>{const out=await api(...args);await new Promise(r=>release=r);return out;};const pending=w.query({context_id:c.context_id},'compare');await new Promise(r=>setImmediate(r));w.humanChange({...w.state,metric:'gross_profit'});release();const r=await pending;await assert.rejects(w.present({result_id:r.result_id,expected_view_version:w.version,view_type:'bar'}),{code:'VIEW_CHANGED'});});
test('cancellation after response prevents caching usable result',async()=>{const w=fixture(),c=w.context(),ctrl=new AbortController(),api=w.api;w.api=async(...args)=>{const r=await api(...args);ctrl.abort();return r;};await assert.rejects(w.query({context_id:c.context_id},'compare',ctrl.signal),{code:'CANCELLED'});assert.equal(w.displayed,null);});
test('cancelled presentation never updates screen',async()=>{const w=fixture(),{c,r}=await prepared(w),ctrl=new AbortController();ctrl.abort();await assert.rejects(w.present(presentation(c,r),ctrl.signal),{code:'CANCELLED'});assert.equal(w.version,1);});
test('undo preserves monotonically increasing version',async()=>{const w=fixture(),{c,r}=await prepared(w);await w.present(presentation(c,r));w.undo();assert.equal(w.version,3);assert.equal(w.displayed,null);await assert.rejects(w.present({...presentation(c,r),expected_view_version:3}),{code:'VIEW_CHANGED'});});
test('second independent presentation cannot overwrite the first',async()=>{const w=fixture(),a=await prepared(w),b=await prepared(w);await w.present(presentation(a.c,a.r));await assert.rejects(w.present(presentation(b.c,b.r)),{code:'VIEW_CHANGED'});});
test('draft retries do not duplicate or overwrite human text',async()=>{const w=fixture(),{r}=await prepared(w),args=draftArgs(r);const first=await w.createDraft(args);w.editDraft(first.draft_id,'人間が編集中');const second=await w.createDraft(args);assert.equal(second.reused,true);assert.equal(w.drafts.length,1);assert.equal(w.drafts[0].text,'人間が編集中');});
test('same idempotency key with different input rejects',async()=>{const w=fixture(),{r}=await prepared(w),args=draftArgs(r);await w.createDraft(args);await assert.rejects(w.createDraft({...args,title:'changed'}),{code:'IDEMPOTENCY_CONFLICT'});});
test('concurrent draft retries create one draft',async()=>{const w=fixture(),{r}=await prepared(w),args=draftArgs(r);await Promise.all([w.createDraft(args),w.createDraft(args)]);assert.equal(w.drafts.length,1);});
test('new draft never edits previous draft',async()=>{const w=fixture(),{r}=await prepared(w),args=draftArgs(r);const a=await w.createDraft(args);w.editDraft(a.draft_id,'keep');await w.createDraft({...args,idempotency_key:'new'});assert.equal(w.drafts.length,2);assert.equal(w.drafts[0].text,'keep');});
test('result authorization is rechecked when draft retries',async()=>{const w=fixture(),{r}=await prepared(w),args=draftArgs(r);await w.createDraft(args);w.api=async()=>{const e=new Error('denied');e.code='FORBIDDEN';throw e;};await assert.rejects(w.createDraft(args),{code:'FORBIDDEN'});});
test('exactly five narrowly scoped tools with correct readonly hints',()=>{const ts=definitions(fixture());assert.equal(ts.length,5);assert.deepEqual(ts.map(t=>t.annotations.readOnlyHint),[true,true,true,false,false]);assert.ok(!ts.some(t=>/send|delete|sql/.test(t.name)));});
test('runtime schema rejects extra arguments, wrong types, bad enums',async()=>{const t=definitions(fixture()).find(t=>t.name==='compare_periods');for(const input of [{context_id:'x',metric:'evil'},{context_id:123},{context_id:'x',limit:101},{context_id:'x',user_id:'admin'}]){const r=await t.execute(input);assert.equal(r.error.code,'INVALID_ARGUMENT');}});
test('schema accepts minimal context-only comparison',()=>{const t=definitions(fixture()).find(t=>t.name==='compare_periods');assert.doesNotThrow(()=>validate(t.inputSchema,{context_id:'ctx'}));});
test('tool wrappers invoke shared methods rather than a second analytics implementation',async()=>{const w=fixture();let called=false;w.query=async()=>{called=true;return {marker:1}};const t=definitions(w).find(t=>t.name==='compare_periods');assert.deepEqual(await t.execute({context_id:'ctx'}),{marker:1});assert.equal(called,true);});
test('registration cleanup contract uses an abort signal (mock, NOT native)',async()=>{let count=0;globalThis.document={modelContext:{registerTool:async()=>{if(++count===3)throw Error('mock fail')}}};const lifetime=new AbortController();const c=await register(fixture(),true,lifetime);assert.equal(c.status,'registration_failed');assert.equal(lifetime.signal.aborted,true);delete globalThis.document;});
