import fs from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import assert from 'node:assert/strict';
import {expect} from 'playwright/test';
import {startLab} from './browser-session.mjs';
const transport = process.env.WEBMCP_TRANSPORT || 'object';
if (!['object','chrome154-json'].includes(transport)) throw new Error('Unknown WEBMCP_TRANSPORT');
const out = 'artifacts/recording';
await fs.mkdir(out,{recursive:true});
await fs.mkdir('docs/media',{recursive:true});
const lab = await startLab({native:true});
const {page} = lab;
const frames = [];
const capture = async (label,seconds=3) => {
  const file = `frame-${String(frames.length).padStart(2,'0')}.png`;
  await page.screenshot({path:`${out}/${file}`});
  frames.push({file,label,seconds});
};
const call = (name,args={}) => page.evaluate(async ({name,args,transport}) => {
  const mc=document.modelContext;
  const tool=(await mc.getTools()).find(t=>t.name===name);
  const result=await mc.executeTool(tool,transport==='chrome154-json'?JSON.stringify(args):args);
  return typeof result==='string'?JSON.parse(result):result;
},{name,args,transport});
try {
  await page.goto(lab.base+'/?test=1');
  await page.waitForFunction(()=>!!window.retailLab);
  await capture('Initial conditions',2);
  let c=await call('get_analysis_context');
  let r=await call('compare_periods',{context_id:c.context_id});
  assert.equal((await call('present_result',{result_id:r.result_id,expected_view_version:c.view_version,view_type:'bar'})).ok,true);
  await expect(page.locator('#kpis')).toContainText('98,000,000');
  await page.screenshot({path:'docs/media/weekly.png',fullPage:true});
  await capture('Native WebMCP: weekly comparison',4);
  c=await call('get_analysis_context');
  r=await call('compare_periods',{context_id:c.context_id,filters:{store_ids:['S03']},group_by:'category'});
  await call('present_result',{result_id:r.result_id,expected_view_version:c.view_version,view_type:'bar'});
  await capture('S03 category breakdown',4);
  c=await call('get_analysis_context');
  r=await call('compare_periods',{context_id:c.context_id});
  await page.selectOption('#metric','gross_profit');
  const stale=await call('present_result',{result_id:r.result_id,expected_view_version:c.view_version,view_type:'bar'});
  assert.equal(stale.error.code,'VIEW_CHANGED');
  await capture('UI change: stale result refused',3);
  c=await call('get_analysis_context');
  r=await call('compare_periods',{context_id:c.context_id});
  assert.equal(r.totals.delta,-624000);
  await call('present_result',{result_id:r.result_id,expected_view_version:c.view_version,view_type:'bar'});
  await capture('Fresh context: gross profit',4);
  await page.screenshot({path:'docs/media/profit.png',fullPage:true});
  await call('create_report_draft',{result_ids:[r.result_id],title:'S03の粗利',notes:'前週比62万4,000円減。原因は未確認。',idempotency_key:'recording-1'});
  await page.locator('#draft-link').click();
  await capture('Unsaved editable draft',4);
  await page.setViewportSize({width:390,height:844});
  await page.goto(lab.base+'/?test=1');
  await page.locator('#compare').click();
  await expect(page.locator('#kpis')).toContainText('98,000,000');
  await page.screenshot({path:'docs/media/mobile.png',fullPage:true});
  await fs.writeFile(`${out}/frames.json`,JSON.stringify({route:'Scripted native document.modelContext calls, not a live Codex recording',browser:lab.browser.version(),transport,frames},null,2));
  await fs.writeFile(`${out}/frames.txt`,frames.map(f=>`file '${f.file}'\nduration ${f.seconds}\n`).join('')+`file '${frames.at(-1).file}'\n`);
  const result=spawnSync('ffmpeg',['-y','-f','concat','-safe','0','-i',`${out}/frames.txt`,'-vf','fps=5,scale=1008:-1:flags=lanczos,split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=bayer','-loop','0','docs/media/demo.gif'],{stdio:'inherit'});
  if(result.error) throw result.error;
  if(result.status!==0) throw new Error('ffmpeg failed');
} finally {await lab.close();}
